export interface Tweet {
  id: string;
  author: string;
  handle: string;
  avatar: string;
  text: string;
  timestamp: string;
  likes: number;
  retweets: number;
  replies: number;
}

export const sampleTweets: Tweet[] = [
  {
    id: '1',
    author: 'Emily Chen',
    handle: '@emilychen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    text: 'Just watched your latest video, absolutely loved the editing! Keep up the great work! 🎬',
    timestamp: '2h ago',
    likes: 24,
    retweets: 5,
    replies: 3,
  },
  {
    id: '2',
    author: 'Marcus Johnson',
    handle: '@marcusj',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    text: 'Interesting perspective, though I\'d have to disagree on some points.',
    timestamp: '3h ago',
    likes: 12,
    retweets: 2,
    replies: 7,
  },
  {
    id: '3',
    author: 'ToxicTroll42',
    handle: '@toxictroll42',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=troll',
    text: 'You\'re literally the worst content creator on this platform. Delete your account.',
    timestamp: '4h ago',
    likes: 1,
    retweets: 0,
    replies: 15,
  },
  {
    id: '4',
    author: 'AnonymousHater',
    handle: '@anon_hater',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anon',
    text: 'Nobody asked for your opinion. Go crawl back to whatever hole you came from 🤡',
    timestamp: '5h ago',
    likes: 3,
    retweets: 1,
    replies: 8,
  },
  {
    id: '5',
    author: 'SarcasmKing',
    handle: '@sarcasmking',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarcasm',
    text: 'Oh wow, another groundbreaking take from the internet\'s greatest mind... /s',
    timestamp: '6h ago',
    likes: 7,
    retweets: 2,
    replies: 4,
  },
  {
    id: '6',
    author: 'IronyMaster',
    handle: '@ironymaster',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=irony',
    text: 'Your content is so original... said absolutely no one ever 😂',
    timestamp: '7h ago',
    likes: 5,
    retweets: 1,
    replies: 6,
  },
  {
    id: '7',
    author: 'DarkThreat',
    handle: '@darkthreat',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dark',
    text: 'I will find where you live. Watch your back.',
    timestamp: '8h ago',
    likes: 0,
    retweets: 0,
    replies: 2,
  },
  {
    id: '8',
    author: 'HatefulUser',
    handle: '@hatefuluser',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hateful',
    text: 'People like you don\'t deserve to exist on this platform or anywhere else.',
    timestamp: '9h ago',
    likes: 2,
    retweets: 0,
    replies: 11,
  },
  {
    id: '9',
    author: 'Sarah Developer',
    handle: '@sarahdev',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    text: 'Great tutorial! This helped me fix my project. Thanks! 🙏',
    timestamp: '10h ago',
    likes: 45,
    retweets: 12,
    replies: 8,
  },
  {
    id: '10',
    author: '用户982',
    handle: '@user982cn',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user982',
    text: '你这种人就不该上网，赶紧滚吧',
    timestamp: '11h ago',
    likes: 0,
    retweets: 0,
    replies: 3,
  },
  {
    id: '11',
    author: 'Alex Thompson',
    handle: '@alexthompson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    text: 'Following your channel for 2 years now, love the growth!',
    timestamp: '12h ago',
    likes: 67,
    retweets: 8,
    replies: 5,
  },
  {
    id: '12',
    author: 'DisappointedViewer',
    handle: '@disappointed',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=disappointed',
    text: 'Unsubscribed. Your content has gone completely downhill. Total garbage.',
    timestamp: '13h ago',
    likes: 4,
    retweets: 1,
    replies: 9,
  },
  {
    id: '13',
    author: 'SpamBot9000',
    handle: '@spambot9000',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=spam',
    text: 'CHECK OUT MY CHANNEL FOR FREE IPHONE GIVEAWAY!!!',
    timestamp: '14h ago',
    likes: 0,
    retweets: 0,
    replies: 0,
  },
  {
    id: '14',
    author: 'CynicUser',
    handle: '@cynicuser',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cynic',
    text: 'What a joke. The world would be better without creators like you spreading nonsense.',
    timestamp: '15h ago',
    likes: 1,
    retweets: 0,
    replies: 7,
  },
  {
    id: '15',
    author: 'Jamie Rodriguez',
    handle: '@jamierodr',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jamie',
    text: 'Really appreciate you covering this topic, it\'s important and underrepresented.',
    timestamp: '16h ago',
    likes: 89,
    retweets: 23,
    replies: 12,
  },
];
